### ISSUE TITLE
action里面的提示和文档不同

### ISSUE THREAD

**Issue by sddwt** [wangziyingwen/AutoApiP#11]
```
Run python ApiOfRead.py
  python ApiOfRead.py
  shell: /usr/bin/bash -e {0}
  env:
    GH_TOKEN: *** 
    GH_REPO: sddwt/AutoApi
    ACCOUNT: ***
    ACCOUNT_ADD: 
    ACCOUNT_DEL: 
    REDIRECT_URI: 
    OTHER_CONFIG: 
    EMAIL: 
    TG_BOT: 
<<<<<<<<<<<<<配置初始化中>>>>>>>>>>>>>
```
请问只有这个输出成功了吗
